import exp from "constants";

const DummyUserData: any = {
  memberNickname: "o3perga2dtg3ion",
  memberDetail:
    " 안녕하세요 사용자01입니다. 가전제품을 전문적으로 경매합니다. 안녕하가전제품을 전문적으로 경매합니다. 안녕하세요 사용자01입니다. 가전제품을 전문적으로 경매합니다. 안녕하세요 사용자01입니다. 가전제품을 전문적으로 경매합니다. 안녕하세요 사용자01입니다. 가전제품을 전문적으로 경매합니다.",
  imgURL: "https://aucation-bucket.s3.ap-northeast-2.amazonaws.com/bear.jpg",
  memberPoint: 1053113,
  currentPage: 0,
  totalPage: 1,
  mypageItems: [
    {
      discountRate: 50,
      discountTitle: "가나다람라발알낭라",
      discountPrice: 1,
      discountDiscountedPrice: 1,
      discountPk: 9,
      discountUUID: "b33v9Eyn",
      discountOwnerPk: null,
      discountCustomerPk: null,
      discountEnd: "2023-11-07T05:40:00",
      historyDatetime: null,
      historyDoneDatetime: null,
      mycity: "대전광역시",
      zipcode: "유성구",
      street: "덕명동",
      isLike: false,
      historyStatus: "BEFORE_CONFIRM",
      customerNicknname: "",
      imgfile:
        "https://aucation-bucket.s3.ap-northeast-2.amazonaws.com/discount/b33v9Eyn/%20KakaoTalk_20230714_165141193_05.jpg",
    },
    {
      discountRate: 50,
      discountTitle: "가나다람라발알낭라",
      discountPrice: 1,
      discountDiscountedPrice: 1,
      discountPk: 7,
      discountUUID: "m0dKC1zm",
      discountOwnerPk: null,
      discountCustomerPk: null,
      discountEnd: "2023-11-07T05:40:00",
      historyDatetime: "2023-11-07T05:40:00",
      historyDoneDatetime: null,
      mycity: "대전광역시",
      zipcode: "유성구",
      street: "덕명동",
      isLike: false,
      historyStatus: "BEFORE_CONFIRM",
      customerNicknname: "",
      imgfile:
        "https://aucation-bucket.s3.ap-northeast-2.amazonaws.com/discount/m0dKC1zm/%20KakaoTalk_20230714_165141193_05.jpg",
    },
    {
      discountRate: 50,
      discountTitle: "가나다람라발알낭라",
      discountPrice: 1000,
      discountDiscountedPrice: 800,
      discountPk: 6,
      discountUUID: "YV5D8EyV",
      discountOwnerPk: null,
      discountCustomerPk: null,
      discountEnd: "2023-11-07T02:10:00",
      historyDatetime: "2023-11-07T05:40:00",
      historyDoneDatetime: "2023-11-08T05:40:00",
      mycity: "대전광역시",
      zipcode: "유성구",
      street: "덕명동",
      isLike: false,
      historyStatus: "AFTER_CONFIRM",
      customerNicknname: "",
      imgfile:
        "https://aucation-bucket.s3.ap-northeast-2.amazonaws.com/discount/YV5D8EyV/%20%EC%B5%9C%EA%B3%A0%EA%B0%80%20%EB%8F%84%EC%9E%A5%20%281%29.png",
    },
    {
      discountRate: 50,
      discountTitle: "가나다람라발알낭라",
      discountPrice: 1,
      discountDiscountedPrice: 1,
      discountPk: 5,
      discountUUID: "gwb4bJPY",
      discountOwnerPk: null,
      discountCustomerPk: null,
      discountEnd: "2023-11-07T05:40:00",
      historyDatetime: null,
      historyDoneDatetime: null,
      mycity: "대전광역시",
      zipcode: "유성구",
      street: "덕명동",
      isLike: false,
      historyStatus: null,
      customerNicknname: "",
      imgfile:
        "https://aucation-bucket.s3.ap-northeast-2.amazonaws.com/discount/gwb4bJPY/%20KakaoTalk_20230714_165141193_05.jpg",
    },
  ],
};

export default DummyUserData;
